import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="py-4">
          <ul className="flex justify-center gap-6">
            <li><Link href='/'>Home</Link></li>
            <li><Link href='/profile'>Profile</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
